result = 5
print('result =',result)
result -= 1
print ('result =',result)
result += 3
print('result =',result)
result = - result 
print('resule =',result)
result = True
print('not result=',not result)